### PR TITLE
[HER-155] Add feature flags

### PR DESCRIPTION
**Pull request by andreea-dumitrascu**
## Description
- Add it in  JSON file
- Create flags for login and  camera live stream

## Related
[HER-155](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?selectedIssue=HER-155)

### CODE REVIEW

**Review by miutamihai — APPROVED** [review]
Looks like you missed writing code :smile:

**Comment by andreea-dumitrascu** [comment]
> Looks like you missed writing code :smile: 

Yes 🥰

**Review by ConstantinescuAndrei — APPROVED** [review]
:+1:

**Review by TBiannca — APPROVED** [review]

**Review by Urzica-Platon-Casian — APPROVED** [review]
gucci!

**Pull request merged**
